### ISSUE TITLE
No such file or directory: './pre_train_data/pretrained_entity_region_spacy.json'

### ISSUE THREAD

**Issue by suexin27** [YuanLi95/FGCL_For_JMERE#1]
Hi~ 当我复现您的代码时，出现了下面的bug，请问可以上传一下这个pretrained_entity_region_spacy.json文件吗？🙏

Traceback (most recent call last):
  File "/home/disk0/sx/FGCL_For_JMERE-main/main.py", line 518, in <module>
    pre_train(args, clip_args)
  File "/home/disk0/sx/FGCL_For_JMERE-main/main.py", line 272, in pre_train
    instances_pretrain = load_data_instances(pre_train_text_path,pre_train_image_path, args, clip_args)
  File "/home/disk0/sx/FGCL_For_JMERE-main/utils/data.py", line 312, in load_data_instances
    text_file = open(text_path,"r",encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: './pre_train_data/pretrained_entity_region_spacy.json'

**Comment by suexin27** [comment]
您好，请问当我调用utils里的程序生成pretrained_entity_region_spacy.json文件时，还是报错：FileNotFoundError: [Errno 2] No such file or directory: '../pre_train_data/pre_train_data.json，请问一下这个pre_train_data的数据是什么呢？能否上传一下，方便复现，谢谢

**Comment by YuanLi95** [comment]
> 您好，请问当我调用utils里的程序生成pretrained_entity_region_spacy.json文件时，还是报错：FileNotFoundError: [Errno 2] No such file or directory: '../pre_train_data/pre_train_data.json，请问一下这个pre_train_data的数据是什么呢？能否上传一下，方便复现，谢谢

不好意思，最近在忙出境访学以及其他论文的事，没有来得及看。我现在正在打包一个服务器上的pre-train data 文件。

**Comment by suexin27** [comment]
> > 您好，请问当我调用utils里的程序生成pretrained_entity_region_spacy.json文件时，还是报错：FileNotFoundError: [Errno 2] No such file or directory: '../pre_train_data/pre_train_data.json，请问一下这个pre_train_data的数据是能否上传一下，方便复现，谢谢
> 
> 不好意思，最近在忙着出境访学以及其他论文的事，没有来得及看。我现在正在备份一个服​​务器上的预训练数据文件。

感谢！期待ing🙏

**Comment by YuanLi95** [comment]
> > > 您好，请问当我调用utils里的程序生成pretrained_entity_region_spacy.json文件时，还是报错：FileNotFoundError: [Errno 2] No such file or directory: '../pre_train_data/pre_train_data.json，请问一下这个pre_train_data的数据是能否上传一下，方便复现，谢谢
> > 
> > 
> > 不好意思，最近在忙着出境访学以及其他论文的事，没有来得及看。我现在正在备份一个服​​务器上的预训练数据文件。
> 
> 感谢！期待ing🙏
或许你可以从中找到你所需要的东西
通过网盘分享的文件：pre_train_data 2.zip
链接: https://pan.baidu.com/s/1po-t0pUC17RDrkYue5fwUw 提取码: ukrx 
--来自百度网盘超级会员v6的分享

**Comment by ShDdu** [comment]
您好，我也想复现这个实验，但百度网盘的链接失效了，能否再分享一次呢，谢谢！

**Comment by louieunnie** [comment]
Hello. I appreciate your wonderful work.

I am also interested in accessing the data for my resarch. If it is not too much trouble, could you kindly share the link again?
I would be truly grateful for your help.

Thank you in advance. Looking forward to your response.

**Comment by wywsunflower** [comment]
> > > > 您好，请问当我调用utils里的程序生成pretrained_entity_region_spacy.json文件时，还是报错：FileNotFoundError: [Errno 2] No such file or directory: '../pre_train_data/pre_train_data.json，请问一下这个pre_train_data的数据是能否上传一下，方便复现，谢谢
> > > 
> > > 
> > > 不好意思，最近在忙着出境访学以及其他论文的事，没有来得及看。我现在正在备份一个服​​务器上的预训练数据文件。
> > 
> > 
> > 感谢！期待ing🙏
> > 或许你可以从中找到你所需要的东西
> > 通过网盘分享的文件：pre_train_data 2.zip
> > 链接: https://pan.baidu.com/s/1po-t0pUC17RDrkYue5fwUw 提取码: ukrx
> > --来自百度网盘超级会员v6的分享

Xin Su同学，你下载到pre_train_data.json文件了吗？
Yuan博士，网盘链接已经失效，什么时候能再次分享？我们一直在关注你们的研究，希望您能提供一个长久的链接信息。

**Comment by YuanLi95** [comment]
> > > > > 您好，请问当我调用utils里的程序生成pretrained_entity_region_spacy.json文件时，还是报错：FileNotFoundError: [Errno 2] No such file or directory: '../pre_train_data/pre_train_data.json，请问一下这个pre_train_data的数据是能否上传一下，方便复现，谢谢
> > > > 
> > > > 
> > > > 不好意思，最近在忙着出境访学以及其他论文的事，没有来得及看。我现在正在备份一个服​​务器上的预训练数据文件。
> > > 
> > > 
> > > 感谢！期待ing🙏
> > > 或许你可以从中找到你所需要的东西
> > > 通过网盘分享的文件：pre_train_data 2.zip
> > > 链接: https://pan.baidu.com/s/1po-t0pUC17RDrkYue5fwUw 提取码: ukrx
> > > --来自百度网盘超级会员v6的分享
> 
> Xin Su同学，你下载到pre_train_data.json文件了吗？ Yuan博士，网盘链接已经失效，什么时候能再次分享？我们一直在关注你们的研究，希望您能提供一个长久的链接信息。


通过网盘分享的文件：pre_train_data 2.zip
链接: https://pan.baidu.com/s/1gO8P-e72lW-9_31BLTia8A?pwd=7rjj 提取码: 7rjj 
--来自百度网盘超级会员v7的分享

**Comment by lijianing0422** [comment]
您好，请问您项目的依赖配置文件（比如requirements.txt）能否提供一下？
